name: Build LKM for KernelSU

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build-lkm.yml"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-lkm.yml"
  workflow_call:
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android14-6.1"
            sub_level: 78
            os_patch_level: 2024-06
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: true
